### ISSUE TITLE
Alex's Caves Incompatible with Distant Horizons [1.20.1]

### ISSUE THREAD

**Issue by V0idshock** [AlexModGuy/AlexsCaves#519]
Alex's Caves is incompatible with Distant Horizons. Though Distant Horizons is currently still in development for MC 1.20.1, this is the only mod out of a complete mod pack that is incompatible with Distant Horizons.

Distant Horizons is a LOD (Level Of Detail) mod that allows for a far greater (pseudo) render distance at the cost of detail. This is not handled by Minecraft's terrain rendering, but a custom pipeline.

The problem might stem from Alex's Caves having some very advanced custom shaders, but mind you, so do other mods from the collection. Only Alex's Caves seem to have issues with compatability.

**Comment by AlexModGuy** [comment]
is it crashing or what

**Comment by MochiVN634** [comment]
> is it crashing or what

Not sure if you've already tested it, but Distant Horizons doesn't generate the LOD terrain with Alex's Caves installed, very weird since it's the only mod I've found so far with that have this incompatibility.

**Comment by V0idshock** [comment]
> is it crashing or what

I am sorry, i feel i came off a bit rude in the first post. To answer the question, no, it is ´technically compatible´ in the way that the two mods do not make the instance crash. The only problem is that the Distant Horizons LOD renderer simply does not render.

**Comment by V0idshock** [comment]
The DH development has since found a temporary fix. The issue seems to stem from Biome Ambient Light Coloring. Simply go into client side configs for Alex's Caves and disable "biome_ambient_light_coloring"

**Comment by JustAnotherBugReporter** [comment]
It's fixed in the latest release of DH (from what I've seen), this can be removed now.

**Comment by AMN-D** [comment]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/129135638/1fbf6332-93f0-49af-a279-275ea7861342)

can some one help here !!!
mine still not working and turning this off does nothing biome_ambient_light_coloring

**Comment by Loreb29** [comment]
> ![image](https://private-user-images.githubusercontent.com/129135638/331882465-1fbf6332-93f0-49af-a279-275ea7861342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjAxOTMsIm5iZiI6MTcxNzgxOTg5MywicGF0aCI6Ii8xMjkxMzU2MzgvMzMxODgyNDY1LTFmYmY2MzMyLTkzZjAtNDlhZi1hMjc5LTI3NWVhNzg2MTM0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNDExMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzIxZmFkMTk2ZDI5NGUzNTAyMmE4N2YxYzk1ZjExNzc0MDY1NDNhNjZjNTg4Njk2M2Q2ZmRhM2MzNDYyNDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bt_7kW9qqLXELQPKO77fXlW-LcxTX6r0QiU0L-rljro)
> 
> can some one help here !!! mine still not working and turning this off does nothing biome_ambient_light_coloring minecraft version 1.20.1 DH 2.0.1 -a Forge 47.2.0

Hey!!, i had the same problem, but it turns out it isn't Alex Cave's fault, DH has a feature called cave culling which limits the depth of the LODs, by default it's seth to 40, so anything below height 40 wont have LOD's, and that includes Alex Cave's Biomes, the option comes enabled by default (due to performance stuff) and can be disabled via:
_DH options button>Advanced Options>Graphics>Advanced Graphics Options>Cave Culling_
You can also decrease the Cave Culling height and it would work too.
Take in account this doesn't fix the other issue discussed at the start of the issue, that's a different problem and if you don't disable that config file option DH won't work.
Screenshots:
![2024-06-07_23 22 46](https://github.com/AlexModGuy/AlexsCaves/assets/102338909/2aaa2e22-30eb-4573-9d72-cc441df95971)
![2024-06-07_23 22 59](https://github.com/AlexModGuy/AlexsCaves/assets/102338909/4aad9fa2-27e6-4b7b-ac09-0f985e562721)
I'm only at 8 chunks
![2024-06-07_23 23 20](https://github.com/AlexModGuy/AlexsCaves/assets/102338909/766d0448-1584-4a2b-9e98-12e1f6c0dfc6)

**Comment by PrinceJaxonHellsing** [comment]
I still seem to be having this issue, and I've even disabled Biome Ambient Light Coloring in the Alex's Caves Client, don't know if something changed at one point or there's something else it's not telling me about.

**Comment by PrinceJaxonHellsing** [comment]
Nvm, some reason changing one of the distant horizons settings fixed it?
